azure_openai:
  api_version: "2024-02-15-preview"
  deployment_name: "gpt-4o-mini"
  temperature: 0.7
  max_tokens: 1000

content_types:
  leadership_content:
    system_prompt: "You are an expert in creating thought leadership content for the data industry."
    max_length: 1000
  
  product_deep_dive:
    system_prompt: "You are an expert in technical product documentation and analysis."
    max_length: 1500
    
  customer_stories:
    system_prompt: "You are an expert in crafting compelling customer success stories."
    max_length: 800
    
  technical_documentation:
    system_prompt: "You are an expert technical writer specializing in data technologies."
    max_length: 2000 

social_media:
  twitter:
    char_limit: 280
  
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587 